#!/usr/bin/env python
# -*- coding:utf-8 -*-

import sys,os
import os.path
import jieba
import jieba.posseg as pseg

def is_chinese_word(u0):
    return u0 >= u'\u4e00' and u0 <= u'\u9fa5'

def do_seg_file(filename, verbose = False):
    f = open(filename)
    txt = f.read()
    f.close()

    #tokens = jieba.cut(txt)
    #for fet in tokens:
        #u0 = fet[0]
        #if not is_chinese_word(u0) :
            #continue
        #if len(fet) < 2:
            #continue
        ##print fet
    
    words = pseg.cut(txt)
    for w in words:
        fet = w.word
        pos = w.flag
        #if pos != 'n' and pos != 'v' and pos != 'vn':
            #continue
        if verbose:
            print fet, pos

def main():
    if os.path.isdir(sys.argv[1]):
        i = 0
        for _, dirnames, filenames in os.walk(root_dir):
            for filename in filenames:
                do_seg_file(os.path.join(root_dir, filename), False)
                if i % 100 == 0:
                    print "[%d] %s" % (i, filename)
                i += 1
    elif os.path.isfile(sys.argv[1]):
        do_seg_file(sys.argv[1], True)

if __name__ == '__main__':
    main()

